export const ActionTypes = {
    ADD_CONTACT : "ADD_CONTACT",
    ADD_FAVOURITE : "ADD_FAVOURITE",
    REMOVE_FAVOURITE : "REMOVE_FAVOURITE",
    REMOVE_CONTACT : "ADD_CONTACT",
    GET_CONTACTS : "GET_CONTACTS",
    GET_FAVOURITES : "GET_FAVOURITES",
    GET_PEOPLE : "GET_PEOPLE",
    PEOPLE_ERROR : "PEOPLE_ERROR",
}