export const ActionTypes = {
    GET_PEOPLE: "GET_PEOPLE",
    FILTER_PEOPLE: "FILTER_PEOPLE",
    FILTER_PEOPLE_BY_LOCATION: "FILTER_PEOPLE_BY_LOCATION",
    UPDATE_PEOPLE: "UPDATE_PEOPLE",
    CREATE_PEOPLE: "CREATE_PEOPLE",
    PEOPLE_ERROR: "PEOPLE_ERROR",
}